{
    "name": "Account Addons",
    "version": "17.0.1.0.1",
    "category": "Learning",
    "summary": "Module for learning website module abilities",
    "website": "https://github.com/6Ministers/odoo-accounting-ru",
    "author": "Digital-autoparts",
    "depends": [
        "sale_management",
        "account",
        "stock",
        "purchase",
        "stock_account",
        "website_sale",
        "point_of_sale",
        "l10n_by",
    ],
    "data": [
        "security/res_user.xml",
        "views/account_chart_template_views.xml",
        "views/actions_fiscal_period.xml",
        "views/account_move_views_by.xml",
        "demo/demo_data.xml",
    ],
    "demo": [],
    "license": "LGPL-3",
}
